INSERT INTO meals (name, price, type_id, half, allergic, vega) VALUES
('Húsleves cérnametélttel', 1200, 1, FALSE, FALSE, FALSE),
('Paradicsomleves betűtésztával', 1100, 1, FALSE, FALSE, TRUE),
('Marhapörkölt galuskával', 3800, 2, FALSE, FALSE, FALSE),
('Rántott csirkecomb', 2500, 2, TRUE, FALSE, FALSE),
('Tárkonyos borjúragu leves', 1500, 1, TRUE, FALSE, FALSE),
('Grill zöldségek', 1800, 3, FALSE, FALSE, TRUE),
('Túrós csusza tepertővel', 2900, 2, FALSE, FALSE, FALSE),
('Cézársaláta csirkével', 2800, 5, FALSE, FALSE, FALSE),
('Gundel palacsinta', 1600, 4, FALSE, TRUE, TRUE),
('Somlói galuska', 1700, 4, FALSE, TRUE, TRUE),
('Fokhagymás-tejfölös lángos', 1900, 2, FALSE, TRUE, TRUE),
('Kapros-túrós rétes', 1400, 4, FALSE, TRUE, TRUE),
('Vadas marha zsemlegombóccal', 4100, 2, FALSE, TRUE, FALSE),
('Szürkeharcsa filé majonézes krumplival', 4500, 2, FALSE, TRUE, FALSE),
('Vegán burger édesburgonyával', 3500, 2, FALSE, FALSE, TRUE),
('Erőleves zöldségekkel', 1300, 1, TRUE, FALSE, TRUE),
('Sült krumpli', 900, 3, TRUE, FALSE, TRUE),
('Görög saláta', 2200, 5, FALSE, FALSE, TRUE),
('Olasz tészta (penne)', 3100, 2, FALSE, TRUE, TRUE),
('Káposztás cvekedli', 2700, 2, TRUE, FALSE, TRUE);
